In [50]:
import numpy as np

def bubble():
    array = np.array([4,3,9,3,1])
    count = 0
    print("original length : ")
    print(array)

    for i in range(len(array)-1):
        flag = False
        for j in range(len(array)-1-i):
            if array[j] > array [j+1]:
                temp = array[j]
                array[j] = array[j+1]
                array[j+1] = temp
                flag = True
                count +=1
        if(not flag):
            break
    print("bubble sort : ")
    print(array)
    print()
    print("number of swapping : ",count)
def test():
    start = time.clock()
    bubble()
    elapsed = (time.clock() - start)
    print("Time taken for bubble = ", elapsed)
    print("Time taken for bubble = ", elapsed)
if __name__ == '__main__':
    import time
    test() 

original length : 
[4 3 9 3 1]
bubble sort : 
[1 3 3 4 9]

number of swapping :  7
Time taken for bubble =  0.0006399999999997519
Time taken for bubble =  0.0006399999999997519


/home/syed/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:25: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
/home/syed/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:27: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead


In [28]:
import numpy as np
def selection():
    array = np.array([4,3,9,3,1])
    count = 0
    print("original length : ")
    print(array)

    for i in range(len(array)-1):
        index = i
        for j in range(i+1,len(array)):
            if array[j] < array[index]:
                index = j
        if array[i] != array[index]:
            temp = array[i]
            array[i] = array[index]
            array[index] = temp
            count +=1
    print("Selection sort : ")
    print(array)
    print()
    print("number of swapping : ",count)
def test():
    start = time.clock()
    selection()
    elapsed = (time.clock() - start)
    print("Time taken for selection = ", elapsed)
    print("Time taken for selection = ", elapsed)
if __name__ == '__main__':
    import time
    test() 

original length : 
[4 3 9 3 1]
Selection sort : 
[1 3 3 4 9]

number of swapping :  3
Time taken for selection =  0.0010200000000000209
Time taken for selection =  0.0010200000000000209


/home/syed/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:23: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
/home/syed/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:25: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead


In [43]:
from numpy import array

def insertion():
    
    array = np.array([4,3,9,3,1])
    count = 0
    print("original length : ")
    print(array)

    for i in range(1,len(array)):
        temp = array[i]
        index = i
        while(index!=0 and array[index-1] > temp):
            array[index] = array[index-1]
            index-=1
        array[index] = temp
        count+=1

    print("Insertion sort : ")
    print(array)
    print()
    print("number of swapping : ",count)

def test():
    start = time.clock()
    insertion()
    elapsed = (time.clock() - start)
    print("Time taken for insertion = ", elapsed)
    print("Time taken for insertion = ", elapsed)
if __name__ == '__main__':
    import time
    test() 


original length : 
[4 3 9 3 1]
Insertion sort : 
[1 3 3 4 9]

number of swapping :  4
Time taken for insertion =  0.000644000000000311
Time taken for insertion =  0.000644000000000311


/home/syed/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:25: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
/home/syed/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:27: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead


In [29]:
import numpy as np

def bubble():
    array = np.array([4,3,9,3,1])
    count = 0
    print("original length : ")
    print(array)

    print("bubble sort : ")
    for i in range(len(array)-1):
        flag = False
        for j in range(len(array)-1-i):
            if array[j] > array [j+1]:
                temp = array[j]
                array[j] = array[j+1]
                array[j+1] = temp
                flag = True
                count +=1
        if(not flag):
            break
    
    
        for i in array:
            print(i,end=" ")
        print()
    print("number of swapping : ",count)

def selection():
    array = np.array([4,3,9,3,1])
    count = 0
    print("original length : ")
    print(array)

    print("Selection sort : ")
    for i in range(len(array)-1):
        index = i
        for j in range(i+1,len(array)):
            if array[j] < array[index]:
                index = j
        if array[i] != array[index]:
            temp = array[i]
            array[i] = array[index]
            array[index] = temp
            count +=1

        for i in array:
            print(i,end=" ")
        print()
    print("number of swapping : ",count)

def insertion():
    
    array = np.array([4,3,9,3,1])
    count = 0
    print("original length : ")
    print(array)

    print("Insertion sort : ")
    for i in range(1,len(array)):
        temp = array[i]
        index = i
        while(index!=0 and array[index-1] > temp):
            array[index] = array[index-1]
            index-=1
        array[index] = temp
        count+=1

        for i in array:
            print(i,end=" ")
        print()
    print("number of swapping : ",count)

def counting():
    arr = array([4,3,9,3,1])
    count = array([0 for i in range(10)])
    for i in range(len(arr)):
        count[arr[i]] =+1
    print(count)
    print()
    for i in range(1,len(count)):
        count[i] += count[i-1]
    print(count)

    sortedArr = array([0 for i in range(len(arr))])

    print("counting sort : ")
    for i in range(len(arr)):
        sortedArr[count[arr[i]] -1] = arr[i]
        count[arr[i]] -=1
    
    
        for i in sortedArr:
            print(i,end=" ")
        print()    

def test():
    start1 = time.clock()
    bubble()
    bubble_time = (time.clock() - start1)
    print()
    start2 = time.clock()
    selection()
    selection_time = (time.clock() - start2)
    print()
    start3 = time.clock()
    insertion()
    insertion_time = (time.clock() - start3)
    print()
    start4 = time.clock()
    counting()
    counting_time = (time.clock() - start4)
    
    print("Time taken for bubble sort = ", bubble_time)
    print("Time taken for selection sort = ", selection_time)
    print("Time taken for insertion sort = ", insertion_time)
    print("Time taken for counting sort = ", counting_time)

if __name__ == '__main__':
    import time
    test() 


original length : 
[4 3 9 3 1]
bubble sort : 
3 4 3 1 9 
3 3 1 4 9 
3 1 3 4 9 
1 3 3 4 9 
number of swapping :  7

original length : 
[4 3 9 3 1]
Selection sort : 
1 3 9 3 4 
1 3 9 3 4 
1 3 3 9 4 
1 3 3 4 9 
number of swapping :  3

original length : 
[4 3 9 3 1]
Insertion sort : 
3 4 9 3 1 
3 4 9 3 1 
3 3 4 9 1 
1 3 3 4 9 
number of swapping :  4

[0 1 0 1 1 0 0 0 0 1]

[0 1 1 2 3 3 3 3 3 4]
counting sort : 
0 0 4 0 0 
0 3 4 0 0 
0 3 4 9 0 
3 3 4 9 0 
1 3 4 9 0 
Time taken for bubble sort =  0.003511000000000042
Time taken for selection sort =  0.004580999999999946
Time taken for insertion sort =  0.008234999999999992
Time taken for counting sort =  0.0020889999999997855


/home/syed/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:97: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
/home/syed/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:99: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
/home/syed/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:101: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
/home/syed/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:103: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
/home/syed/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:105: Deprecatio

In [38]:
import numpy as np
arr = np.array([2,5,1,0,4,7,9,3,-2,10,15,20])
even = np.array([0 for i in range(6)])
odd = np.array([0 for i in range(6)])

a=0
b=0

print("input array: ",arr)

for i in range(len(arr)):
    if arr[i]%2==0:
        even[a] = arr[i]
        a+=1
    else:
        odd[b] = arr[i]
        b+=1
        
for i in range(len(even)-1):
    for j in range(len(even)-1-i):
        if even[j] > even[j+1]:
            temp = even[j]
            even[j] = even[j+1]
            even[j+1] = temp
            
for i in range(len(odd)-1):
    for j in range(len(odd)-1-i):
        if odd[j] < odd[j+1]:
            temp = odd[j]
            odd[j] = odd[j+1]
            odd[j+1] = temp
            
            
for i in range(len(arr)):
    if i< len(even):
        arr[i] = even[i]
    else:
        arr[i] = odd[i-6]

print("output array: ",arr)

input array:  [ 2  5  1  0  4  7  9  3 -2 10 15 20]
output array:  [-2  0  2  4 10 20 15  9  7  5  3  1]
